baseurl = "https://www.go-siris.com/"
languageCode = "en-us"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
contentDir = "content"
publishDir = "docs"
title = "SIRIS Docs"
theme = "siris-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""


[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true

[params]
	# General information
	author = "go-siris"
	description = "A material design theme for documentations."
	copyright = "Released under the BSD-3-Clause license"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/go-siris/siris"

	pkgTitle = "SIRIS"
	version = "7.3.4"
	logo = "images/go-siris.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "blue"
    	accent  = "orange"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[social]
	twitter = ""
	github  = "go-siris"
	email   = "docs@go-siris.com"

[Languages]
[Languages.en]
weight = 1
LanguageName = "English"
languageCode = "en-us"

	[Languages.en.blackfriday]
	angledQuotes = false

	[[Languages.en.menu.main]]
	url    = "/"
	name   = "SIRIS"
	weight = 1
	identifier = "siris-start"

[Languages.de]
weight = 5
LanguageName = "Deutsch"
languageCode = "de"

[Languages.de.permalinks]

	[Languages.de.Taxonomies]
	plaque = "tags"

	[[Languages.de.menu.main]]
	url    = "/"
	name   = "SIRIS"
	weight = 1
	identifier = "siris-start"

[Languages.fr]
weight = 10
LanguageName = "Français"
languageCode = "fr-fr"

[Languages.fr.permalinks]

	[Languages.fr.Taxonomies]
	plaque = "plaques"

	[[Languages.fr.menu.main]]
	url    = "/"
	name   = "SIRIS"
	weight = 1
	identifier = "siris-start"

[Languages.zh-cn]
weight = 15
LanguageName = "简体中文"
languageCode = "zh-cn"

[Languages.zh-cn.permalinks]

	[Languages.zh-cn.Taxonomies]
	plaque = "标签"

	[[Languages.zh-cn.menu.main]]
	url    = "/"
	name   = "SIRIS"
	weight = 1
	identifier = "siris-start"
