baseurl = "https://example.org/"
languageCode = "en-us"
DefaultContentLanguage = "en"
title = "SIRIS Docs"
theme = "siris-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	author = "go-siris"
	description = "A material design theme for documentations."
	copyright = "Released under the BSD-3-Clause license"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/go-siris/siris"

  pkgTitle = "SIRIS"
	version = "1.0.0"
	logo = "images/go-siris.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "blue"
    	accent  = "orange"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[social]
	twitter = ""
	github  = "Dexus"
	email   = "github@josef-froehle.de"

[Languages]
[Languages.en]
weight = 1
LanguageName = "English"
[Languages.en.blackfriday]
angledQuotes = false

[[Languages.en.menu.main]]
url    = "/"
name   = "SIRIS"
weight = 1

[[Languages.en.menu.main]]
url    = "/getting-started/"
name   = "Getting started"
weight = 10

[[Languages.en.menu.main]]
url    = "/adding-content/"
name   = "Adding content"
weight = 20

[[Languages.en.menu.main]]
url    = "/roadmap/"
name   = "Roadmap"
weight = 30

[[Languages.en.menu.main]]
url    = "/license/"
name   = "License"
weight = 40

[Languages.fr]
weight = 10
LanguageName = "Français"
languageCode = "fr-fr"

[Languages.fr.Taxonomies]
plaque = "plaques"

[[Languages.fr.menu.main]]
url    = "/"
name   = "SIRIS"
weight = 1

[[Languages.fr.menu.main]]
url    = "/getting-started/"
name   = "Getting started"
weight = 10

[[Languages.fr.menu.main]]
url    = "/adding-content/"
name   = "Adding content"
weight = 20

[[Languages.fr.menu.main]]
url    = "/roadmap/"
name   = "Roadmap"
weight = 30

[[Languages.fr.menu.main]]
url    = "/license/"
name   = "License"
weight = 40

[Languages.de]
weight = 5
LanguageName = "Deutsch"
languageCode = "de"

[Languages.de.Taxonomies]
plaque = "tags"

[[Languages.de.menu.main]]
url    = "/"
name   = "SIRIS"
weight = 1

[[Languages.de.menu.main]]
url    = "/anfangen/"
name   = "Anfangen"
weight = 10

[[Languages.de.menu.main]]
url    = "/inhalt-hinzufügen/"
name   = "Inhalt hinzufügen"
weight = 20

[[Languages.de.menu.main]]
url    = "/fahrplan/"
name   = "Fahrplan"
weight = 30

[[Languages.de.menu.main]]
url    = "/lizenz/"
name   = "Lizenz"
weight = 40

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
